/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMatchDayRouteImport } from './routes/_authenticated/match-day'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSquadIndexRouteImport } from './routes/_authenticated/squad/index'
import { Route as AuthenticatedSquadPlayerIdRouteImport } from './routes/_authenticated/squad/$playerId'
import { Route as AuthenticatedMatchSummarySessionIdRouteImport } from './routes/_authenticated/match-summary/$sessionId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMatchDayRoute = AuthenticatedMatchDayRouteImport.update({
  id: '/match-day',
  path: '/match-day',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSquadIndexRoute = AuthenticatedSquadIndexRouteImport.update({
  id: '/squad/',
  path: '/squad/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSquadPlayerIdRoute =
  AuthenticatedSquadPlayerIdRouteImport.update({
    id: '/squad/$playerId',
    path: '/squad/$playerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchSummarySessionIdRoute =
  AuthenticatedMatchSummarySessionIdRouteImport.update({
    id: '/match-summary/$sessionId',
    path: '/match-summary/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/home': typeof AuthenticatedHomeRoute
  '/match-day': typeof AuthenticatedMatchDayRoute
  '/match-summary/$sessionId': typeof AuthenticatedMatchSummarySessionIdRoute
  '/squad/$playerId': typeof AuthenticatedSquadPlayerIdRoute
  '/squad/': typeof AuthenticatedSquadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/home': typeof AuthenticatedHomeRoute
  '/match-day': typeof AuthenticatedMatchDayRoute
  '/match-summary/$sessionId': typeof AuthenticatedMatchSummarySessionIdRoute
  '/squad/$playerId': typeof AuthenticatedSquadPlayerIdRoute
  '/squad': typeof AuthenticatedSquadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/match-day': typeof AuthenticatedMatchDayRoute
  '/_authenticated/match-summary/$sessionId': typeof AuthenticatedMatchSummarySessionIdRoute
  '/_authenticated/squad/$playerId': typeof AuthenticatedSquadPlayerIdRoute
  '/_authenticated/squad/': typeof AuthenticatedSquadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/calendar'
    | '/home'
    | '/match-day'
    | '/match-summary/$sessionId'
    | '/squad/$playerId'
    | '/squad/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/calendar'
    | '/home'
    | '/match-day'
    | '/match-summary/$sessionId'
    | '/squad/$playerId'
    | '/squad'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/calendar'
    | '/_authenticated/home'
    | '/_authenticated/match-day'
    | '/_authenticated/match-summary/$sessionId'
    | '/_authenticated/squad/$playerId'
    | '/_authenticated/squad/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/match-day': {
      id: '/_authenticated/match-day'
      path: '/match-day'
      fullPath: '/match-day'
      preLoaderRoute: typeof AuthenticatedMatchDayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/squad/': {
      id: '/_authenticated/squad/'
      path: '/squad'
      fullPath: '/squad/'
      preLoaderRoute: typeof AuthenticatedSquadIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/squad/$playerId': {
      id: '/_authenticated/squad/$playerId'
      path: '/squad/$playerId'
      fullPath: '/squad/$playerId'
      preLoaderRoute: typeof AuthenticatedSquadPlayerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/match-summary/$sessionId': {
      id: '/_authenticated/match-summary/$sessionId'
      path: '/match-summary/$sessionId'
      fullPath: '/match-summary/$sessionId'
      preLoaderRoute: typeof AuthenticatedMatchSummarySessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMatchDayRoute: typeof AuthenticatedMatchDayRoute
  AuthenticatedMatchSummarySessionIdRoute: typeof AuthenticatedMatchSummarySessionIdRoute
  AuthenticatedSquadPlayerIdRoute: typeof AuthenticatedSquadPlayerIdRoute
  AuthenticatedSquadIndexRoute: typeof AuthenticatedSquadIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMatchDayRoute: AuthenticatedMatchDayRoute,
  AuthenticatedMatchSummarySessionIdRoute:
    AuthenticatedMatchSummarySessionIdRoute,
  AuthenticatedSquadPlayerIdRoute: AuthenticatedSquadPlayerIdRoute,
  AuthenticatedSquadIndexRoute: AuthenticatedSquadIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
